In [6]:
from pathlib import Path
import zipfile

ruta = Path("../Datos/originales/denue")

print("¿Existe la carpeta?:", ruta.exists())

archivos = list(ruta.glob("*"))

for archivo in archivos:
    print(archivo.name)

    if archivo.suffix.lower() == ".zip":
        with zipfile.ZipFile(archivo) as zip:
            for nombre in zip.namelist():
                print("  ", nombre)

¿Existe la carpeta?: True
denue_09_csv.zip
   diccionario_de_datos/denue_diccionario_de_datos.csv
   conjunto_de_datos/denue_inegi_09_.csv
   metadatos/metadatos_denue.txt

In [7]:
import pandas as pd
import zipfile

ruta = "../Datos/originales/denue/denue_09_csv.zip"

with zipfile.ZipFile(ruta) as zip:
    with zip.open("conjunto_de_datos/denue_inegi_09_.csv") as archivo:
        df = pd.read_csv(archivo, encoding="latin-1", low_memory=False)

print("Filas:", df.shape[0])
print("Columnas:", df.shape[1])

display(df.head())

Filas: 462732
Columnas: 42

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,...,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta
0,12299604,09017112519000021000000000U5,ACUARIO AQUAVIRTUAL,NaN,112519,Otra acuicultura,0 a 5 personas,CALLE,PROCURADURIA GENERAL DE JUSTICIA,CALLE,...,Venustiano Carranza ...,1204,1,5.584307e+09,KUINO2106@GMAIL.COM,NaN,Fijo,19.418880,-99.090126,2026-04
1,11845788,09013112515000091000000000U5,AJOLOTARIO APATLACO,NaN,112519,Otra acuicultura,0 a 5 personas,OTRO(ESPECIFIQUE),NINGUNO,CALLE,...,Apatlaco ...,1281,800,5.577368e+09,EDUARDOSANCHEVALDERRAMA@GMAIL.COM,NaN,Fijo,19.264524,-99.089505,2025-05
2,11845785,09013112515000071000000000U7,AJOLOTARIO CARRIZAL,NaN,112519,Otra acuicultura,0 a 5 personas,OTRO(ESPECIFIQUE),NINGUNO,CALLE,...,Isla de las Muñecas ...,1281,800,5.526720e+09,NaN,NaN,Fijo,19.275685,-99.101824,2025-05
3,11845786,09013112515000082000000000U4,AJOLOTARIO CHINAMPA ONKALI,ONKALI,112519,Otra acuicultura,6 a 10 personas,OTRO(ESPECIFIQUE),CANAL,CALLE,...,Xochimilco ...,1099,34,5.518275e+09,NaN,NaN,Fijo,19.277486,-99.097971,2025-05
4,11845789,09013112515000102000000000U0,AJOLOTARIO TLAZOCAMA TONANA,NaN,112519,Otra acuicultura,6 a 10 personas,OTRO(ESPECIFIQUE),CANAL,CALLEJON,...,Xochimilco ...,1099,15,NaN,ORTADAVID294@GMAIL.COM,NaN,Fijo,19.274853,-99.101802,2025-05

In [8]:
print(df.columns.tolist())

['id', 'clee', 'nom_estab', 'raz_social', 'codigo_act', 'nombre_act', 'per_ocu', 'tipo_vial', 'nom_vial', 'tipo_v_e_1', 'nom_v_e_1', 'tipo_v_e_2', 'nom_v_e_2', 'tipo_v_e_3', 'nom_v_e_3', 'numero_ext', 'letra_ext', 'edificio', 'edificio_e', 'numero_int', 'letra_int', 'tipo_asent', 'nomb_asent', 'tipoCenCom', 'nom_CenCom', 'num_local', 'cod_postal', 'cve_ent', 'entidad', 'cve_mun', 'municipio', 'cve_loc', 'localidad', 'ageb', 'manzana', 'telefono', 'correoelec', 'www', 'tipoUniEco', 'latitud', 'longitud', 'fecha_alta']

In [9]:
# Filtrar comercio al por menor de abarrotes y alimentos
df_4611 = df[
    df["codigo_act"].astype(str).str.startswith("4611")
].copy()

print("Total de establecimientos:", len(df_4611))

display(df_4611.head())

Total de establecimientos: 86931

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,...,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta
50263,12314487,09016461190003831000000000U3,NaN,NaN,461190,Comercio al por menor de otros alimentos,0 a 5 personas,CALLE,FERROCARRIL DE CUERNAVACA,AVENIDA,...,Miguel Hidalgo ...,0571,26,NaN,LAESPERANZAOFICIAL@GMAIL.COM,WWW.ESPERANZA.MX,Fijo,19.442484,-99.192315,2026-04
50266,12313686,09007461130115122000000000U7,NaN,NaN,461130,Comercio al por menor de frutas y verduras fre...,6 a 10 personas,CIRCUITO,SUBASTA Y PRODUCTORES,CIRCUITO,...,Iztapalapa ...,2475,8,NaN,NaN,NaN,Fijo,19.369334,-99.086454,2026-04
50267,12313603,09007461130115221000000000U7,NaN,NaN,461130,Comercio al por menor de frutas y verduras fre...,0 a 5 personas,CALLE,NINGUNO,CIRCUITO,...,Iztapalapa ...,2475,5,NaN,NaN,NaN,Fijo,19.370664,-99.087451,2026-04
50268,12312672,09013461110048401000000000U7,NaN,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,MIRADOR,CERRADA,...,Xochimilco ...,1440,1,5.572284e+09,NaN,NaN,Fijo,19.226676,-99.088607,2026-04
50269,12313561,09007461130114983000000000U3,NaN,NaN,461130,Comercio al por menor de frutas y verduras fre...,11 a 30 personas,CALLE,MILITARES,CIRCUITO,...,Iztapalapa ...,2475,5,NaN,GUERREROPRODUCTOR@PRODIGY.NET.MX,NaN,Fijo,19.368405,-99.094867,2026-04

In [10]:
df_4611.groupby(
    ["codigo_act", "nombre_act"]
).size().reset_index(name="Establecimientos")

,codigo_act,nombre_act,Establecimientos
0,461110,"Comercio al por menor en tiendas de abarrotes,...",38996
1,461121,Comercio al por menor de carnes rojas,6411
2,461122,Comercio al por menor de carne de aves,7123
3,461123,Comercio al por menor de pescados y mariscos,638
4,461130,Comercio al por menor de frutas y verduras fre...,13165
5,461140,Comercio al por menor de semillas y granos ali...,2892
6,461150,"Comercio al por menor de leche, otros producto...",4796
7,461160,Comercio al por menor de dulces y materias pri...,7149
8,461170,Comercio al por menor de paletas de hielo y he...,1872
9,461190,Comercio al por menor de otros alimentos,3889

In [11]:
from pathlib import Path

ruta_salida = Path("../Datos/procesados")
ruta_salida.mkdir(parents=True, exist_ok=True)

# Guardar en Parquet
df_4611.to_parquet(
    ruta_salida / "denue_4611_cdmx_2026.parquet",
    index=False
)

# Guardar en CSV
df_4611.to_csv(
    ruta_salida / "denue_4611_cdmx_2026.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Archivos guardados correctamente")
print("Registros:", len(df_4611))
print("Columnas:", len(df_4611.columns))

Archivos guardados correctamente
Registros: 86931
Columnas: 42